name: publish

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      repository:
        default: pypi
        type: string
    secrets:
      twine_token:
        required: true
      CODECOV_TOKEN:
        required: false
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (for example: 1.2.3)'
        type: string
        required: true
      repository:
        description: 'Package index repository'
        type: choice
        options:
          - pypi
          - testpypi
        default: pypi

run-name: publish to ${{ inputs.repository }}

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: publish to ${{ inputs.repository }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --group dev
      - name: force right version
        run: |
          .github/change_version.py --set '${{ inputs.version }}'
      - name: Build
        run: uv run pyproject-build
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.twine_token }}
        run: |
          uv run pyproject-build
          uv run twine upload --verbose --repository ${{ inputs.repository }} dist/*
      - name: highlight
        run: |
          INDEX=""
          if [ "${{ inputs.repository }}" != "pypi" ]; then
            INDEX=" -i ${{ inputs.repository }}"
          fi
          cat <<EOF >> ${GITHUB_STEP_SUMMARY}
          \`telecodex\` uploaded to ${{ inputs.repository }}
          \`\`\`
          pip install${INDEX} telecodex==${{ inputs.version }}
          \`\`\`
          EOF
